version: '3.8'  # Add version for compatibility
services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'  # Map host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data to a volume
volumes:
  pgdata:  # Define a named volume for PostgreSQL data